### ISSUE TITLE
no way to crash on programmer errors?

### ISSUE THREAD

**Issue by davepacheco** [trentm/node-cmdln#12]
Sorry if I've asked this before.  I thought I had, but can't find the issue.  My node-cmdln program is blowing an assertion:

```
$ ./bin/manta-hk dircount-audit report 64a512e5-7e4d-c7b6-9f20-81d017c3dbed
manta-hk dircount-audit: error: args.jobPath (string) is required
```

There's no stack or anything.  I tried setting DEBUG in the environment, and using node with --abort-on-uncaught-exception, setting showErrStack on the class itself, and setting showErrStack in the constructor options, but I couldn't manage to get a stack trace.  I patched "showErrStack" to true here:
https://github.com/trentm/node-cmdln/blob/c4e1b3805d32c7932a7df620541326b38bfbdfa8/lib/cmdln.js#L900-L901

and _did_ get a stack trace.  But it would be really nice to be able to get a core file with --abort-on-uncaught-exception. :)

**Comment by trentm** [comment]
Curious on your opinions here, @davepacheco. 

This is happening mainly because of this try/catch to catch exceptions in handler code (i.e. in "do_SUBCMD" functions): https://github.com/trentm/node-cmdln/blob/327524852a02517637ede20f47dd41e69a5306c5/lib/cmdln.js#L696-L715
and also to a lesser degree by this one for errors in option processing: https://github.com/trentm/node-cmdln/blob/327524852a02517637ede20f47dd41e69a5306c5/lib/cmdln.js#L673

I could make this configurable. Do you think node-cmdln should *not*-try/catch by default? It would be a behaviour change, so a major ver bump, but that would be fine.

**Comment by davepacheco** [comment]
For my own stuff, I'd much prefer that the CLI (not the cmdln framework) gracefully identify operational errors, print them out, and exit if appropriate.  I don't want the framework to catch every exception that gets thrown, print the message, and exit, for all the usual reasons: I'd rather reserve thrown exceptions for programmer errors, and I'd rather the command-line tool abort (however ungracefully) when those happen.  I don't know who all feels the same way.  If there's consensus on this, then I think it's worth flipping the default and bumping the major version.  If not, I don't care to try to convince people.  I'd take a config variable that lets me opt into that behavior.

**Comment by trentm** [comment]
I AM THE LAW^W consensus.

**Comment by trentm** [comment]
This'll be in cmdln@5
